name: npm

on:
    push:
        branches:
            - master
            - 'dev-*'

jobs:
    build-test-deploy:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - name: Install node ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Checkout ðŸ›Žï¸
              uses: actions/checkout@v2

            - name: Enviroment
              env:
                  API_URL: ${{ secrets.API_URL_DEV }}
                  FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY_DEV }}
                  FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT_DEV }}
              run: |
                  jsonFile=package.json
                  node > out_${jsonFile} <<EOF
                  //Read data
                  var data = require('./${jsonFile}');

                  //Manipulate data
                  data.homepage = 'https://lfmachadodasilva.github.io/myexpenses-ui';

                  //Output data
                  console.log(JSON.stringify(data));

                  EOF

                  mv out_${jsonFile} ${jsonFile}

                  envsubst < util/.env.template > .env

            - name: Install  ðŸ› 
              run: npm install

            - name: Build ðŸ“¦
              run: npm run build:github

            - name: Test ðŸ”Œ
              run: npm run test:coverage

            - name: Deploy ðŸš€
              uses: JamesIves/github-pages-deploy-action@releases/v3
              with:
                  ACCESS_TOKEN: '${{ secrets.GITHUB_PAGES }}'
                  BRANCH: gh-pages
                  FOLDER: build
